project_id = "djumpimcwzhjujysznox"

[functions.acerola-ai-gateway]
verify_jwt = true

[functions.acerola-image]
verify_jwt = true

[functions.acerola-media]
verify_jwt = true

[functions.acerola-music]
verify_jwt = true

[functions.acerola-live-session]
verify_jwt = true

[functions.paystack-payment]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
